---
apiVersion: v1
kind: Pod
metadata:
  name: infra-master
  labels:
    app: infra-server
spec:
  containers:
    - name: main-container
      image: donbattery/infra_server:latest
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: infra-service
spec:
  type: NodePort
  selector:
    app: infra-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
...